# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickFlight' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuickFlight

  pod 'Alamofire', '~> 4.8.2'

  target 'QuickFlightTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QuickFlightUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
